name: SonarCloud Analysis

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        name: Build and Analyze
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: "11"

            - name: Run Maven SonarQube Analysis for Backend
              run: |
                cd back  
                mvn clean verify sonar:sonar -Dsonar.projectKey=msjemenblc_ci-cd-project

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies for Frontend
              run: |
                cd front
                npm install

            - name: Run SonarQube Analysis for Frontend
              run: npx sonar-scanner
