name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    name: Build & Analyze (Backend + Frontend)
    runs-on: ubuntu-latest

    steps:
      # Etape 1 : Récupérer le code du repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Etape 2 : Installer JDK 11 nécessaire pour le backend Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Etape 3 : Cacher les dépendances SonarQube pour accélérer les builds suivants
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Etape 4 : Cacher les dépendances Maven pour accélérer les builds suivants
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Etape 5 : Compiler et tester le backend avec Maven
      - name: Build & Test Backend
        run: |
          cd back
          mvn -B verify

      # Etape 6 : Installer SonarScanner globalement pour analyser le frontend
      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner

      # Etape 7 : Analyser le backend avec SonarCloud en utilisant le plugin Maven
      - name: Run SonarCloud Analysis for Backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn sonar:sonar \
            -Dsonar.projectKey=msjemenblc_bobapp-backend \
            -Dsonar.organization=msjemenblc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      
      # Etape 8 : Installer les dépendances du frontend
      - name: Install Frontend Dependencies
        run: |
          cd front
          npm install

      # Etape 9 : Analyser le frontend avec SonarCloud
      - name: Run SonarCloud Analysis for Frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd front
          sonar-scanner \
            -Dsonar.projectKey=msjemenblc_bobapp-frontend \
            -Dsonar.organization=msjemenblc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}